### ISSUE TITLE
Is it possible add  some tolerance/threshold as a parameter

### ISSUE THREAD

**Issue by ryanrosello-og** [manykarim/robotframework-imagecompare#2]
Hi,

I've got this failing test when I run it across different test environments.  To me, these images look identical.  Just wondering if there is a way to add some sort of tolerance/threshold parameter to avoid false negatives?

![2023-04-04_16-02-38](https://user-images.githubusercontent.com/50574915/229701932-0cd6c2b5-40da-42c1-87aa-ee7be6a44f4d.jpg)

![ec12a3a9-d2ad-11ed-93b7-cc96e5d0f916_page_1_rectangles_concat](https://user-images.githubusercontent.com/50574915/229702261-b07afa9d-f208-4221-b852-556821ddc45c.jpg)
![ec1402e4-d2ad-11ed-8aae-cc96e5d0f916_page_1_blended](https://user-images.githubusercontent.com/50574915/229702265-3e6548d6-a788-400d-b1c9-ed3ebf9ca7ce.jpg)

**Comment by manykarim** [comment]
Hi @ryanrosello-og , yes there is a parameter for that.
When importing the Library, you can set an argument `threshold` with a value between 0.000 and 1.000
0.000 = exact comparison

If the value is higher, the images may differ more.
It's the same as in my DocTest Library (for visual document testing):
https://manykarim.github.io/robotframework-doctestlibrary/VisualTest.html#library-documentation-top

```
*** Settings ***
Library    ImageCompare    threshold=0.1
```

Most likely, the difference in your two pictures is caused by the .jgp compression.
To avoid that in general, you can try to save the images in your application in some lossless format like .png instead of .jpg.

I hope I soon find some time to update this Library and it's documentation.
In the meantime, if you want to use some more features like Text Recognition or other ways of ignoring areas or accepting small differences, I recommend to check out the https://github.com/manykarim/robotframework-doctestlibrary.
It has more dependencies (like some pdf packages) but it is better maintained at the moment. And it can also be used for image comparison.

**Comment by ryanrosello-og** [comment]
thanks!  Yeah I missed it in the docs.  Good to know this already exist 👍
